networks:
  wishflow:
volumes:
  wishflow_postgres:
  wishflow_app_node_modules:

services:
  postgres:
    image: postgres:15
    container_name: wishflow_postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - wishflow
    ports:
      - ${POSTGRES_EXTERNAL_PORT:-5432}:5432
    restart: always
    volumes:
      - wishflow_postgres:/var/lib/postgresql/data

  wishflow_app_dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      postgres:
        condition: service_healthy
    container_name: wishflow_app_dev
    profiles:
      - dev
    networks:
      - wishflow
    ports:
      - ${APP_EXTERNAL_PORT:-8080}:8080
      - 9229:9229
    volumes:
      - wishflow_app_node_modules:/app/node_modules
      - .:/app
